// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6D74RtyHL0AbjMzrtfrt-r8E2HUeatQ',
    appId: '1:804592188556:web:fd4c0e3cb519a326d9cfa9',
    messagingSenderId: '804592188556',
    projectId: 'ramadan-companion-app-bacfc',
    authDomain: 'ramadan-companion-app-bacfc.firebaseapp.com',
    storageBucket: 'ramadan-companion-app-bacfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzx4MMYPW6r2-f87569hSye-y__y3kBo',
    appId: '1:804592188556:android:a7c09b999c63ca1fd9cfa9',
    messagingSenderId: '804592188556',
    projectId: 'ramadan-companion-app-bacfc',
    storageBucket: 'ramadan-companion-app-bacfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBILBD-uIKrj4N9ZOjg54HNKbzSRrx5w',
    appId: '1:804592188556:ios:b7d74b3ffea13691d9cfa9',
    messagingSenderId: '804592188556',
    projectId: 'ramadan-companion-app-bacfc',
    storageBucket: 'ramadan-companion-app-bacfc.firebasestorage.app',
    iosBundleId: 'com.example.ramadancompanionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJBILBD-uIKrj4N9ZOjg54HNKbzSRrx5w',
    appId: '1:804592188556:ios:b7d74b3ffea13691d9cfa9',
    messagingSenderId: '804592188556',
    projectId: 'ramadan-companion-app-bacfc',
    storageBucket: 'ramadan-companion-app-bacfc.firebasestorage.app',
    iosBundleId: 'com.example.ramadancompanionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ6D74RtyHL0AbjMzrtfrt-r8E2HUeatQ',
    appId: '1:804592188556:web:f33bf87a358a09f0d9cfa9',
    messagingSenderId: '804592188556',
    projectId: 'ramadan-companion-app-bacfc',
    authDomain: 'ramadan-companion-app-bacfc.firebaseapp.com',
    storageBucket: 'ramadan-companion-app-bacfc.firebasestorage.app',
  );
}